flaskproject/apps/front/forms.py
from wtforms import Form,ValidationError
from wtforms.fields import StringField,IntegerField, FileField
from flask_wtf.file import FileAllowed, FileSize
from wtforms.validators import Email, length, EqualTo, Length, InputRequired

from exts import cache
from models import UserModel
from flask import request

class BaseForm(Form):
    @property
    def messages(self):
        message_list = []
        if self.errors:
            for errors in self.errors.values():
                message_list.extend(errors)
            return message_list

class RegisterForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确的邮箱！")])
    email_captcha = StringField(validators=[Length(4,4,message="请输入正确的验证码！")])
    username = StringField(validators=[Length(3,30,message="请输入正确长度的用户名！")])
    password = StringField(validators=[Length(6,20,message="请输入正确长度的密码！")])
    repeat_password = StringField(validators=[EqualTo("password",message="两次密码不一致！")])
    graph_captcha = StringField(validators=[Length(4,4,message="请输入正确长度的图形验证码！")])

    def validate_email(self,field):
        email = field.data
        user = UserModel.query.filter_by(email =email).first()
        if user:
            raise ValidationError(message="邮箱已经被注册！")

    def validate_email_captcha(self,field):
        email_captcha = field.data
        email = self.email.data
        cache_captcha = cache.get(email)
        if not cache_captcha or email_captcha != cache_captcha:
            raise ValidationError(message="邮箱验证码错误！")

    def validate_graph_captcha(self,field):
        key = request.cookies.get("_graph_captcha_key")
        cache_captcha = cache.get(key)
        graph_captcha = field.data
        if not cache_captcha or cache_captcha.lower() != graph_captcha.lower():
            raise ValidationError(message="图形验证码错误！")


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确的邮箱！")])
    password = StringField(validators=[Length(6,20,message="请输入正确长度的密码！")])
    remember = IntegerField()


class UploadAvatarForm(BaseForm):
    image = FileField(validators=[FileAllowed(['jpg','jpeg','png'],message='请上传.jpg .jpeg .png等格式图片'),
                                  FileSize(max_size=1024*1024*5,message='图片最大不超过5M')])


class UploadImageForm(BaseForm):
    image = FileField(validators=[FileAllowed(['jpg','jpeg','png'],message='请上传.jpg .jpeg .png等格式图片'),
                                  FileSize(max_size=1024*1024*2,message='图片最大不超过2M')])


class SetSignatureForm(BaseForm):
    signature = StringField(validators=[Length(0,20,message="个性签名不大于20字！")])


class PublicPostForm(BaseForm):
    title = StringField(validators=[Length(min=1, max=200, message="帖子标题必须在1-200之间！")])
    content = StringField(validators=[InputRequired(message='请传入内容！')])
    board_id = IntegerField(validators=[InputRequired(message='请传入板块ID!')])


class PublicCommentForm(BaseForm):
    content = StringField(validators=[InputRequired(message='请传入内容！')])
    post_id = IntegerField(validators=[InputRequired(message="请传入帖子ID")])

flaskproject/apps/front/__init__.py
from apps.front.views import bp as front_bp

flaskproject/apps/front/views.py
import json
import os.path
from flask import (Blueprint,
                   request,
                   render_template,
                   jsonify,
                   current_app,
                   make_response,
                   session,
                   redirect,
                   g, url_for)
import string
import random

from flask_jwt_extended import create_access_token
from flask_mail import Message
from flask_paginate import get_page_parameter, Pagination

from exts import mail,cache
from utils import restful
from utils.captcha import Captcha
import time
from hashlib import md5
from io import BytesIO
from .forms import RegisterForm, LoginForm, UploadAvatarForm, SetSignatureForm, UploadImageForm, PublicPostForm, \
    PublicCommentForm
from models import UserModel, Stockdatabase, PostModel, BoardModel, CommentModel
from exts import db
from .decorators import login_required
from flask_avatars import Identicon
from sqlalchemy.sql import func

bp = Blueprint("apps", __name__, url_prefix='/')


#befor_request
@bp.before_request
def front_before_request():
    if 'user_id' in session:
        user_id = session.get('user_id')
        user = UserModel.query.get(user_id)
        setattr(g, "user", user)
@bp.context_processor
def front_context_processor():
    if hasattr(g, "user"):
        return {"user": g.user}
    else:
        return {}

@bp.route('/')
def index():
    sort = request.args.get("st",type=int,default=1)
    # posts = PostModel.query.order_by(PostModel.create_time.desc()).all()
    post_query = None
    if sort == 1:
        post_query = PostModel.query.order_by(PostModel.create_time.desc())
    else:
        post_query = db.session.query(PostModel).outerjoin(CommentModel).group_by(
            PostModel.id).order_by(func.count(CommentModel.id).desc(),PostModel.create_time.desc())

    total = post_query.count()
    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = request.args.get("per_page", type=int, default=current_app.config['PER_PAGE_COUNT'])
    # print(page)
    start = (page-1)*current_app.config['PER_PAGE_COUNT']
    end = start+current_app.config['PER_PAGE_COUNT']
    posts = post_query.slice(start, end)
    pagination = Pagination(bs_version=3, page=page, link_size='sm',
                            prev_label='上一页',next_label='下一页',
                            per_page=per_page, total=total)
    # pagination = Pagination(page=page, per_page=per_page, total=total,
    #                         search=False, record_name='items',
    #                         css_framework='bootstrap4',
    #                         link_size='sm',
    #                         show_single_page=False,
    #                         page_parameter='page',
    #                         per_page_parameter='per_page')
    # boards = BoardModel.query.order_by(BoardModel.create_time.desc()).all()

    # 获取第一支股票数据作为首页默认图标数据
    # price_json_data = json.loads(Stockdatabase.query.get(1).PRICE_datajson)
    # default_code = price_json_data['data']['code']   #股票代码
    # default_name = price_json_data['data']['name']   #股票名称
    # default_klines =price_json_data['data']['klines']
    # default_klines_time = []
    # default_klines_price =[]
    # for default_kline in default_klines:
    #     default_kline_split = default_kline.split(",")
    #     default_klines_time.append(default_kline_split[0])
    #     default_klines_price.append(default_kline_split[2])
    context = {
        "posts": posts,
        "pagination": pagination,
        "st": sort,
        # "default_code": default_code,
        # "default_name": default_name,
        # "default_klines_time": default_klines_time,
        # "default_klines_price": default_klines_price,
    }
    return render_template('front/index.html', **context)


@bp.get('/cms')
def cms():
    return render_template('cms/index.html')

@bp.route('/post/public/',methods=['GET','POST'])
@login_required
def public_post():
    if request.method=="GET":   #如果GET访问就返回主页
        posts = PostModel.query.all()
        return render_template("front/index.html",posts=posts)
    else:
        form = PublicPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            board_id = form.board_id.data
            try:
                board = BoardModel.query.get(board_id)
            except Exception as e:
                return restful.params_error(message="板块不存在!")
            post_model = PostModel(title=title,content=content,board = board,author=g.user)
            db.session.add(post_model)
            db.session.commit()
            return restful.ok(data={"id":post_model.id})
        else:
            return restful.params_error(message=form.messages[0])


@bp.get("/email/captcha")  #直接get模式
def email_captcha():
    #/email/captcha?email=wangshiyu217@163.com
    email = request.args.get("email")
    if not email:
        return restful.params_error(message="请先传入邮箱！")
    source = list(string.digits)
    captcha = "".join(random.sample(source,4))
    subject = "【自游数据】您的注册验证码:%s" % captcha
    recipients = [email]
    body = "【自游数据】您的注册码为：%s" % captcha
    current_app.celery.send_task("send_mail", (email, subject, body))
    cache.set(email, captcha)
    # print(cache.get(email))
    return restful.ok(message="邮件发送成功！")


@bp.route('/graph/captcha/')
def graph_captcha():
    captcha, image = Captcha.gene_graph_captcha()
    #key, value
    key = md5((captcha+str(time.time())).encode('utf-8')).hexdigest()
    cache.set(key,captcha)
    out = BytesIO()
    image.save(out,'png')
    out.seek(0)
    resp = make_response(out.read())
    resp.content_type = 'image/png'
    resp.set_cookie("_graph_captcha_key",key,max_age = 3600)
    return resp


@bp.route('/login/',methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("front/login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                return restful.params_error("邮箱或密码错误！")
            if not user.check_password(password):
                return restful.params_error("邮箱或密码错误！")
            session['user_id'] = user.id
            #如果是员工，才生成token
            token = ""
            if user.is_internal_employee:
                token = create_access_token(identity=user.id)
            if remember==1:
                # 默认浏览器关闭则过期
                session.permanent = True
            return restful.ok(data={"token": token, "user": user.to_dict()})
        else:
            return restful.params_error(message=form.messages[0])

@bp.route("/logout/")
def logout():
    session.clear()
    return redirect('/')


@bp.route('/register/',methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("front/register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            identicon = Identicon()
            filenames = identicon.generate(text=md5(email.encode('utf-8')).hexdigest())
            avatar = filenames[2]
            user = UserModel(email=email,username=username,password=password,avatar=avatar)
            db.session.add(user)
            db.session.commit()
            return restful.ok()

        else:
            message = form.messages[0]
            return restful.params_error(message=message)


@bp.route('/setting/')
@login_required
def setting():
    email_hash = md5(g.user.email.encode("utf-8")).hexdigest()
    return render_template('front/setting.html',email_hash=email_hash)

@bp.post("/avatar/upload/")
@login_required
def upload_avatar():
    form = UploadAvatarForm(request.files)
    if form.validate():
        image = form.image.data
        filename = image.filename
        _, ext = os.path.splitext(filename)
        filename = md5((g.user.email+str(time.time())).encode("utf-8")).hexdigest() + ext
        image_path = os.path.join(current_app.config['AVATARS_SAVE_PATH'], filename)
        image.save(image_path)
        g.user.avatar = filename
        db.session.commit()
        return restful.ok(data={'avatar': filename})
    else:
        message = form.messages[0]
        return restful.params_error(message=message)


@bp.post("/signature/edit/")
@login_required
def set_signature():
    form = SetSignatureForm(request.form)
    if form.validate():
        signature = form.signature.data
        g.user.signature = signature
        db.session.commit()
        return restful.ok()
    else:
        return restful.params_error(message=form.messages[0])


@bp.post("/post/image/upload")
@login_required
def upload_post_image():
    form = UploadImageForm(request.files)
    if form.validate():
        image = form.image.data
        filename = image.filename
        _, ext = os.path.splitext(filename)
        filename = md5((g.user.email+str(time.time())).encode("utf-8")).hexdigest() + ext
        image_path = os.path.join(current_app.config['POST_IMAGE_SAVE_PATH'], filename)
        image.save(image_path)
        return jsonify({"errno": 0,
                        "data": {
                        "url": url_for("media.get_post_image",filename=filename),
                        "alt": filename,
                        "href": ""
                        }})
    else:
        message = form.messages[0]
        return jsonify({
                    "errno": 1,
                    "message": message
                })


@bp.get("/post/detail/<post_id>")
def post_detail(post_id):
    try:
        post_model = PostModel.query.get(post_id)
    except:
        return "404"

flaskproject/apps/media/views.py
from flask import Blueprint, send_from_directory, current_app

bp = Blueprint("media", __name__, url_prefix="/media")

#/media/avatar/abc.jpg
# 部署的时候，在nginx中配置一个/media前缀的URL
#访问/media 的时候，我们指定让他从media 文件夹下寻找文件


@bp.route("/avatar/<filename>")
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@bp.route("/post/<filename>")
def get_post_image(filename):
    return send_from_directory(current_app.config['POST_IMAGE_SAVE_PATH'], filename)


@bp.route("/banner/<filename>")
def get_banner_image(filename):
    return send_from_directory(current_app.config['BANNER_IMAGE_SAVE_PATH'], filename)

flaskproject/templates/front/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{url_for('static',filename='front/js/zyajax.js')}}"></script>
    <script src="{{url_for('static',filename='front/js/zyparam.js')}}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{url_for('static',filename='front/css/front_base.css')}}">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
{#    <link rel="stylesheet" href="{{url_for('static',filename='apps/css/sign_base.css')}}">#}
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">韭菜根儿—让价值投资变简单...</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
{#                <ul class="nav navbar-nav">#}
{#                    <li class="active"><a href="/">首页<span class="sr-only">(current)</span></a></li>#}
{#                </ul>#}
{#                <form class="navbar-form navbar-left">#}
{#                    <div class="form-group">#}
{#                        <input type="text" class="form-control" placeholder="请输入关键字">#}
{#                    </div>#}
{#                    <button type="submit" class="btn btn-default">搜索</button>#}
{#                </form>#}
                <ul class="nav navbar-nav navbar-right">
                    {% if user %}
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            {{ user.username }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <li><a href="{{url_for('apps.cms')}}">后台管理</a></li>
                            <li><a href="{{url_for('apps.setting')}}">设置</a></li>
                            <li><a href="{{url_for('apps.logout')}}">注销</a></li>
                        </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('apps.login') }}">登录</a></li>
                        <li><a href="{{ url_for('apps.register') }}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="main-container">
        {% block body %}{% endblock %}
    </div>
</body>

</html>

flaskproject/templates/front/index.html
{% extends "front/base.html" %}

{% block title %}
韭菜根儿--价值投资
{% endblock %}

{% block head %}
{#<script src="https://unpkg.com/@wangeditor/editor@latest/dist/index.js"></script>#}

{#<script src="{{ url_for('static',filename='lib/wangEditor/wangEditor.min.js') }}"></script>#}
{#<script src="{{ url_for('static',filename='front/js/public_post.js') }}"></script>#}
<script src="{{ url_for('static',filename='front/js/stockdata_echart.js') }}"></script>
{#<link rel="stylesheet" href="{{ url_for('static',filename='lib/wangEditor/wangEditor.css') }}">#}
<script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static',filename='front/css/index.css') }}">
{#<link href="https://unpkg.com/@wangeditor/editor@latest/dist/css/style.css" rel="stylesheet">#}
{#<style>#}
{#  #editor—wrapper {#}
{#    border: 1px solid #ccc;#}
{#    z-index: 60; /* 按需定义 */#}
{#  }#}
{#  #toolbar-container { border-bottom: 1px solid #ccc; }#}
{#  #editor-container { height: 500px; }#}
{#</style>#}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-11 col-lg-7"
                 id="lineChartContainer"
                 style="background-color: rgba(218,218,218,0.47);width: 600px;height:500px;">
                <p>{{ default_code }}</p>
                <p>{{ default_name }}</p>
            </div>
            <div class="col-sm-0 col-md-1 col-lg-5"
                style="background-color: rgba(155,125,49,0.1);
                box-shadow: inset 1px -1px 1px #444,
                inset -1px 1px 1px #444;">
                <ul class="post-group-head">
              {% if st ==1 %}
                <li class="active">
              {% else %}
                <li>
              {% endif %}
                 <a href="{{url_for("apps.index",st=1)}}">最新</a>
                </li>
{#              <li><a href="{{ url_for("apps.index",st=2) }}">点赞最多</a></li>#}
              {% if st ==3%}
                <li class="active">
              {% else %}
                <li>
              {% endif %}
                 <a href="{{url_for("apps.index",st=3)}}">评论最多</a>
                </li>
          </ul>
                <ul class="post-list-group">
              {% for post in posts %}
              <li>
                <div class="author-avatar-group">
                  <img src="{{url_for('media.get_avatar',filename=post.author.avatar)}}" alt="">
                </div>
                <div class="post-info-group">
                  <p class="post-title">
                    <a href="{{url_for('apps.post_detail',post_id=post.id)}}">{{post.title}}</a>
                  </p>
                  <p class="post-info">
                    <span>作者：{{post.author.username}}</span>
                    <span>发表时间：{{ post.create_time}}</span>
                    <span>评论:{{ post.comments|length }}</span>
                  </p>
                </div>
              </li>
              {% endfor %}
          </ul>
                <div style="text-align: center">
                {{ pagination.links }}
                </div>
            </div>

{#            <div class="col-sm-0 col-md-0 col-lg-4"#}
{#                style="background-color: #dedef8;#}
{#                box-shadow: inset 1px -1px 1px #444,#}
{#                inset -1px 1px 1px #444;">#}
{##}
{#                <h1 style="text-align:center;padding: 20px;">发布帖子</h1>#}
{#                <form action="" method="post">#}
{#      <div class="form-group">#}
{#        <div class="input-group">#}
{#          <span class="input-group-addon">标题</span>#}
{#          <input type="text" class="form-control" name="title">#}
{#        </div>#}
{#      </div>#}
{#      <div class="form-group">#}
{#        <div class="input-group">#}
{#          <span class="input-group-addon">板块</span>#}
{#          <select name="board_id" class="form-control">#}
{#            <option value="1">公开/public</option>#}
{#            <option value="2">私有/private</option>#}
{#          </select>#}
{#        </div>#}
{#      </div>#}
{#      <div class="form-group">#}
{#        <div id="editor—wrapper">#}
{#        <div id="toolbar-container"></div>#}
{#        <div id="editor-container"></div>#}
{#      </div>#}
{#      </div>#}
{#      <div class="form-group">#}
{#        <button class="btn btn-danger" id="submit-btn">发布帖子</button>#}
{#      </div>#}
{#    </form>#}
{#             </div>#}
        </div>
    </div>



{% endblock body %}

flaskproject/templates/front/login.html
{% extends "front/base.html" %}


{% block title %}
登录 -自游数据
{% endblock %}


{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='front/css/sign_base.css') }}">
    <script src ="{{ url_for('static',filename='front/js/login.js') }}"></script>
{% endblock %}


{% block body %}
        <div class="outer-box">
            <div class="logo-box">
                <a href="/">
                    <img src="{{url_for('static',filename='front/images/logo.png')}}" alt="">
                </a>
            </div>
            <h2 class="page-title">
                韭菜根儿-登录
            </h2>
            <div class="sign-box">
                <div class="form-group">
                    <input type="text" class="form-control" name="email" placeholder="邮箱">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="remember" value="1">记住我
                    </label>
                </div>
                <div class="form-group">
                    <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
                </div>
                <div class="form-group">
                    <a href="#" class="signup-link">没有账号？立即注册</a>
                    <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
                </div>
            </div>
        </div>
{% endblock %}

flaskproject/templates/front/post_detail.html
{% extends "front/base.html" %}

{% block title %}
{{ post.title }} - 自游数据
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='front/css/post_detail.css') }}">
<script src ="{{ url_for('static',filename='front/js/post_detail.js') }}"></script>
{% endblock %}

{% block body %}
    <div class="post-container">
      <h2>{{post.title}}</h2>
      <p class="post-info-group">
        <span>发表时间：{{ post.create_time}}</span>
        <span>作者：{{post.author.username}}</span>
        <span>所属板块：{{ post.board.name }}</span>
        <span>评论数：{{ comment_count }}</span>
      </p>
      <div class="post-content">
          {{ post.content|safe }}
      </div>
    <div class="comment-group">
      <h3>评论列表</h3>
      <ul class="comment-list-group">
          {% for comment in post.comments %}
         <li>
          <div class="avatar-group">
            <img src="{{url_for('media.get_avatar',filename=post.author.avatar)}}" alt="..." class="img-circle" id="avatar-img">
          </div>
          <div class="comment-content">
            <p class="author-info">
              <span>{{comment.author.username}}</span>
              <span>{{ comment.create_time}}</span>
            </p>
            <p class="comment-txt">
                {{comment.content}}
            </p>
          </div>
        </li>
           {% endfor %}
      </ul>
    </div>
    <div class="add-comment-group">
      <h3 >发表评论</h3>
        <textarea name="comment" id="comment-textarea" style="width: 100%; resize:vertical;"></textarea>
      <div class="comment-btn-group">
        <button class="btn btn-primary" id="comment-btn" data-post-id="{{ post.id }}" data-user-id="{{ user.id }}">发表评论</button>
      </div>
    </div>
    </div>
{% endblock %}

flaskproject/templates/front/register.html
{% extends "front/base.html" %}


{% block title %}
注册 -韭菜根儿
{% endblock %}


{% block head %}
<link rel="stylesheet" href="{{ url_for('static',filename='front/css/sign_base.css') }}">
<script src="{{ url_for('static',filename='front/js/register.js') }}"></script>
{% endblock %}


{% block body %}
        <div class="outer-box">
            <div class="logo-box">
                <a href="/">
                    <img src=7"{{url_for('static',filename='front/images/logo.png')}}" alt="">
                </a>
            </div>
            <h2 class="page-title">
                韭菜根儿-注册
            </h2>
            <div class="sign-box">
                <div class="form-group">
                    <div class="input-group">
                        <input type="email" class="form-control" name="email" placeholder="邮箱">
                        <span class="input-group-btn">
                            <button id="email-captcha-btn" class="btn btn-default">发送验证码</button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="email-captcha" placeholder="邮箱验证码">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="用户名">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="密码">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="repeat-password" placeholder="确认密码">
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" name="graph-captcha" placeholder="图形验证码">
                        <span class="input-group-addon captcha-addon">
                            <img id="captcha-img" class="captcha-img" src="{{url_for('apps.graph_captcha')}}" alt="">
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
                </div>
            </div>
        </div>
{% endblock %}

flaskproject/templates/front/setting.html
{% extends 'front/base.html' %}

{% block title %}
    个人设置-自游数据
{% endblock %}

{% block head %}
    <script src="{{ url_for('static',filename='front/js/setting.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/index.css') }}">
    <style>
    body{
      background-color: #f3f3f3;
    }
    .setting-group {
      width: 800px;
      background-color: #ffffff;
      margin: 0 auto;
      padding: 50px;
    }
    #avatar-img{
      width: 140px;
      height: 140px;
    }
  </style>
{% endblock %}

{% block body %}
  <div class="main-container">
    <div class="setting-group">
      <h1>{{user.username}}</h1>
      <div style="height: 20px;"></div>
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱：</label>
          <input type="email" class="form-control" value="{{ user.email}}" readonly>
        </div>
        <div class="form-group">
          <label>头像：</label>
          <div class="input-group">
            <img src="{{url_for('media.get_avatar',filename=user.avatar)}}" alt="..." class="img-circle" id="avatar-img">
            <input type="file" id="avatar-input" accept="image/jpeg, image/png">
          </div>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">个性签名：</label>
          <input type="text" class="form-control" id="signature-input" value="{{ user.signature or "" }}">
        </div>
        <button type="submit" id="submit-btn" class="btn btn-primary">保存</button>
      </form>
    </div>
  </div>
{% endblock %}